[ADD] SearchPage and AppContext
WanderAR-app/WebApp pull request #11
Opened 2023-10-21 18:59 UTC by ancadeau

2023-10-22 15:52 UTC, CyrilDehaese requested changes
passe les svg dans des fichier au moins et retire le react icon si possible sinon pas grave

2023-10-22 15:52 UTC, CyrilDehaese commented on package.json
> +    "react-icons": "^4.11.0",
c'est non

2023-10-22 15:52 UTC, CyrilDehaese commented on src/Components/List/ListElements/RoomImage.tsx
> +              fill="#1758F1"
c'est bof ca ce sertait mieux d'avoir le svg en ressource

2023-10-22 15:52 UTC, CyrilDehaese commented on src/Components/List/ListElements/RoomImage.tsx
> +                  d="M6.372 10.626C6.168 10.698 5.832 10.698 5.628 10.626C3.888 10.032 0 7.55401 0 3.354C0 1.5 1.494 0 3.336 0C4.428 0 5.394 0.528 6 1.344C6.606 0.528 7.578 0 8.664 0C10.506 0 12 1.5
same

2023-10-23 12:46 UTC, CyrilDehaese approved these changes

2023-10-23 12:46 UTC, ancadeau commented on package.json
> +    "react-icons": "^4.11.0",
On verra plus tard !

2023-10-23 12:46 UTC, ancadeau commented on src/Components/List/ListElements/RoomImage.tsx
> +              fill="#1758F1"
On verra plus tard !

2023-10-23 12:47 UTC, ancadeau commented on src/Components/List/ListElements/RoomImage.tsx
> +                  d="M6.372 10.626C6.168 10.698 5.832 10.698 5.628 10.626C3.888 10.032 0 7.55401 0 3.354C0 1.5 1.494 0 3.336 0C4.428 0 5.394 0.528 6 1.344C6.606 0.528 7.578 0 8.664 0C10.506 0 12 1.5
On verra plus tard !

2023-10-23 12:47 UTC, merged